# Generated by Django 5.2 on 2025-05-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='slot_duration',
            field=models.TimeField(verbose_name='Продолжительность приема'),
        ),
    ]
